### ISSUE TITLE
How can i use tableview controller and cell  inside App  ?

### ISSUE THREAD

**Issue by IOSDeveloperProgrammer** [EzimetYusup/WormTabStrip#10]
@EzimetYusup  Thanks for giving library! i need to populating tableview data. 
` func WTSviewOfTab(index: Int) -> UIView {
        let view:LeaveTableVC = LeaveTableVC()
        if index == 0 {
            view.view.backgroundColor = UIColor.black
        } `
  
    self.tableview.delegate = self
        self.tableview.dataSource = self,  `

Error: fatal error: unexpectedly found nil while unwrapping an Optional value

I was getting tableview.delegate = self (in leavetableVC class)
Please help me out this issue

**Comment by EzimetYusup** [comment]
@IOSDeveloperProgrammer can u send me the project or your ViewController?

**Comment by EzimetYusup** [comment]
@IOSDeveloperProgrammer   please check new example.
