### ISSUE TITLE
Crash @ selectTabAt

### ISSUE THREAD

**Issue by a2zZuhaib** [EzimetYusup/WormTabStrip#11]
WormTabStrip.selectTabAt(index: 1) 
Crash if try to set index 1 as default from  [vc1,vc2]

**Comment by EzimetYusup** [comment]
@a2zZuhaib  just tested out, not crashing for me, make sure use
```
 viewPager.currentTabIndex = 3
```
before calling 
```
viewPager.buildUI()
```
to set default index, use selectTabAt after 
```
viewPager.buildUI()
```
