### ISSUE TITLE
Better Readme

### ISSUE THREAD

**Issue by lfarah** [EzimetYusup/WormTabStrip#2]
Hey, your library is really interesting.

The only problem I found was the ```README.md```, which lacks information.
I created this [iOS Open source Readme Template](https://github.com/awesome-labs/iOS-readme-template) so you can take a look on how to better organize.
If you want, I can help you to do it.

What are your thoughts?

**Comment by EzimetYusup** [comment]
@lfarah  yeah, sure let's do this, make it better together!^^

**Comment by EzimetYusup** [comment]
@lfarah Hey, I did bunch of update since last time, check it out, how do you think now? is it better? I used your [ iOS Open source Readme Template ](url) , that was really helpful ^^

**Comment by lfarah** [comment]
Hey @EzimetYusup, perfect! 👍
