### ISSUE TITLE
How to call viewWillAppear while change tab

### ISSUE THREAD

**Issue by rajesh-loganathan** [EzimetYusup/WormTabStrip#26]
How to call `viewWillAppear` of selected `viewController` whenever `tabBar` button pressed or `scrollView` swiped. 

By default `viewWillAppear` not triggered after used this library.

@EzimetYusup

**Comment by EzimetYusup** [comment]
@rajesh-loganathan  pull the latest changes i made the fix so will will appear and view will did Disappear will be triggered as user select the tabs.
