### ISSUE TITLE
CocoaPods

### ISSUE THREAD

**Issue by lfarah** [EzimetYusup/WormTabStrip#3]
I'd be cool to also add Cocoapods support. I did this implementation myself last week for my library. Just follow [this post](https://guides.cocoapods.org/making/making-a-cocoapod.html) and [this checklist](https://github.com/thellimist/EZPods).

**Comment by EzimetYusup** [comment]
@lfarah  Thanks, it really helps.

**Comment by EzimetYusup** [comment]
@lfarah  finally get chance to add the repo to CocoaPods, also made PR in Awesome IOS Lib, please review, Thanks!
