### ISSUE TITLE
blank grey between view controller how to fix it ?

### ISSUE THREAD

**Issue by jesuasir007** [EzimetYusup/WormTabStrip#31]
It's show the blank grey spaces between the view controller when tap
![Screenshot 2021-11-17 at 1 04 01 PM](https://user-images.githubusercontent.com/37362805/142156005-7db9fdf7-9252-46b9-9a13-34b37a6c8ab1.png)
 .

**Comment by EzimetYusup** [comment]
@jesuasir007  Are you sure this is library issue? is the View inside ur viewController fill the width of your view controller?
Please try to run the demo app, if it is same, I can take a look.

**Comment by jesuasir007** [comment]
i have fixed thanx for your response .
