### ISSUE TITLE
How can we add viewcontrollers inside each tabindex?  I mean the first problem is to pass model from main viewcontroller

### ISSUE THREAD

**Issue by Gerald93** [EzimetYusup/WormTabStrip#5]

**Comment by EzimetYusup** [comment]
@Gerald93  please see this  [example](https://github.com/EzimetYusup/WormTabStrip/blob/master/WormTabStrip/WormTabStrip/Example/ExampleViewController.swift#L33).

**Comment by Gerald93** [comment]
thanks, i mean to pass model. Is it possible from root to child?

**Comment by EzimetYusup** [comment]
@Gerald93  Sorry, I did not understand the question, can you explain me with more details, so I can help you to solve the problem.

**Comment by IOSDeveloperProgrammer** [comment]
@Gerald93  Yes, i am having same problem. how to populate tableview data.

**Comment by EzimetYusup** [comment]
@IOSDeveloperProgrammer @Gerald93  you don't have to give tableview it self, but regular ViewController.view for WTSviewOfTab delegate.
