### ISSUE TITLE
Center selected tab

### ISSUE THREAD

**Issue by MinhNguyenVan** [EzimetYusup/WormTabStrip#6]
Can we center the selected tab like Android version with attribute stl_indicatorAlwaysInCenter ?

**Comment by EzimetYusup** [comment]
@MinhNguyenVan  currently not, but we can add it in next version.

**Comment by EzimetYusup** [comment]
Hi @MinhNguyenVan ,
I added centering the selected tab feature, by default it will center it, you can set it by [this property ](https://github.com/EzimetYusup/WormTabStrip/blob/f59342a1559b2a9ac4cf3fb0dbb2464f2f09ae28/WormTabStrip/WormTabStrip/WormLib/WormTabStrip.swift#L100) of WormTabStrip.
