### ISSUE TITLE
index at 1

### ISSUE THREAD

**Issue by irwan33** [EzimetYusup/WormTabStrip#8]
how first load at index 1?

**Comment by EzimetYusup** [comment]
@irwan33 can you elaborate this in more detail?

**Comment by irwan33** [comment]
I tried how to first load in index 1 or index 2 example: tab 2 or tab 3

**Comment by EzimetYusup** [comment]
when you say load, does it mean by default tab2 selected?

**Comment by irwan33** [comment]
Yes that's what i mean

**Comment by EzimetYusup** [comment]
@irwan33  I have updated the repo, please check [viewPager.currentIndex](https://github.com/EzimetYusup/WormTabStrip#usage-example)
